spring.application.name=ContadorDeImpactos
spring.datasource.url=jdbc:postgresql://localhost:5432/contador_de_impactos
spring.datasource.username=postgres
spring.datasource.password=@ndrey1212AA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true